[2025-02-13T21:20:46.608+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T21:20:46.627+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_collection.fetch_and_store_crypto_data scheduled__2024-03-31T21:17:00+00:00 [queued]>
[2025-02-13T21:20:46.637+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_collection.fetch_and_store_crypto_data scheduled__2024-03-31T21:17:00+00:00 [queued]>
[2025-02-13T21:20:46.637+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-13T21:20:46.658+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_and_store_crypto_data> on 2024-03-31 21:17:00+00:00
[2025-02-13T21:20:46.664+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6024) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-13T21:20:46.665+0000] {standard_task_runner.py:72} INFO - Started process 6032 to run task
[2025-02-13T21:20:46.665+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_collection', 'fetch_and_store_crypto_data', 'scheduled__2024-03-31T21:17:00+00:00', '--job-id', '17887', '--raw', '--subdir', 'DAGS_FOLDER/crypto_dag.py', '--cfg-path', '/tmp/tmppfmvxvsb']
[2025-02-13T21:20:46.666+0000] {standard_task_runner.py:105} INFO - Job 17887: Subtask fetch_and_store_crypto_data
[2025-02-13T21:20:46.698+0000] {task_command.py:467} INFO - Running <TaskInstance: crypto_data_collection.fetch_and_store_crypto_data scheduled__2024-03-31T21:17:00+00:00 [running]> on host 7e1fe653b817
[2025-02-13T21:20:46.785+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_data_collection' AIRFLOW_CTX_TASK_ID='fetch_and_store_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-31T21:17:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-31T21:17:00+00:00'
[2025-02-13T21:20:46.786+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T21:20:46.857+0000] {logging_mixin.py:190} INFO - Erreur lors de la récupération des données CoinGecko : 429 Client Error: Too Many Requests for url: https://api.coingecko.com/api/v3/simple/price?ids=bitcoin%2Cethereum&vs_currencies=usd
[2025-02-13T21:20:46.858+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-13T21:20:46.865+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T21:20:46.866+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=crypto_data_collection, task_id=fetch_and_store_crypto_data, run_id=scheduled__2024-03-31T21:17:00+00:00, execution_date=20240331T211700, start_date=20250213T212046, end_date=20250213T212046
[2025-02-13T21:20:46.959+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T21:20:46.970+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T21:20:46.973+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
