[2025-02-12T23:35:32.798+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T23:35:32.815+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_collection.fetch_and_store_crypto_data scheduled__2023-10-09T20:15:00+00:00 [queued]>
[2025-02-12T23:35:32.823+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_collection.fetch_and_store_crypto_data scheduled__2023-10-09T20:15:00+00:00 [queued]>
[2025-02-12T23:35:32.824+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-12T23:35:32.875+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_and_store_crypto_data> on 2023-10-09 20:15:00+00:00
[2025-02-12T23:35:32.883+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=39555) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-12T23:35:32.885+0000] {standard_task_runner.py:72} INFO - Started process 39565 to run task
[2025-02-12T23:35:32.883+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_collection', 'fetch_and_store_crypto_data', 'scheduled__2023-10-09T20:15:00+00:00', '--job-id', '13285', '--raw', '--subdir', 'DAGS_FOLDER/crypto_dag.py', '--cfg-path', '/tmp/tmptio5tg9v']
[2025-02-12T23:35:32.885+0000] {standard_task_runner.py:105} INFO - Job 13285: Subtask fetch_and_store_crypto_data
[2025-02-12T23:35:32.933+0000] {task_command.py:467} INFO - Running <TaskInstance: crypto_data_collection.fetch_and_store_crypto_data scheduled__2023-10-09T20:15:00+00:00 [running]> on host be7ba0dd3a47
[2025-02-12T23:35:33.032+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_data_collection' AIRFLOW_CTX_TASK_ID='fetch_and_store_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-09T20:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-09T20:15:00+00:00'
[2025-02-12T23:35:33.033+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-12T23:35:33.135+0000] {logging_mixin.py:190} INFO - Données récupérées : {'Response': 'Error', 'Message': 'You are over your rate limit please upgrade your account!', 'HasWarning': False, 'Type': 99, 'RateLimit': {'calls_made': {'second': 1, 'minute': 61, 'hour': 4555, 'day': 12760, 'month': 12760, 'total_calls': 12760}, 'max_calls': {'second': 20, 'minute': 300, 'hour': 3000, 'day': 7500, 'month': 11000}}, 'Data': {}}
[2025-02-12T23:35:33.138+0000] {logging_mixin.py:190} INFO - Erreur lors de l'insertion dans PostgreSQL : string indices must be integers, not 'str'
[2025-02-12T23:35:33.150+0000] {logging_mixin.py:190} INFO - Données uploadées dans MinIO.
[2025-02-12T23:35:33.151+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-12T23:35:33.160+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-12T23:35:33.160+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=crypto_data_collection, task_id=fetch_and_store_crypto_data, run_id=scheduled__2023-10-09T20:15:00+00:00, execution_date=20231009T201500, start_date=20250212T233532, end_date=20250212T233533
[2025-02-12T23:35:33.219+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T23:35:33.237+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T23:35:33.242+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
