[2025-02-13T20:59:45.613+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T20:59:45.633+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_collection.fetch_and_store_crypto_data scheduled__2023-11-27T23:17:00+00:00 [queued]>
[2025-02-13T20:59:45.641+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_collection.fetch_and_store_crypto_data scheduled__2023-11-27T23:17:00+00:00 [queued]>
[2025-02-13T20:59:45.641+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-13T20:59:45.671+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_and_store_crypto_data> on 2023-11-27 23:17:00+00:00
[2025-02-13T20:59:45.677+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4172) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-13T20:59:45.677+0000] {standard_task_runner.py:72} INFO - Started process 4180 to run task
[2025-02-13T20:59:45.677+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_collection', 'fetch_and_store_crypto_data', 'scheduled__2023-11-27T23:17:00+00:00', '--job-id', '14887', '--raw', '--subdir', 'DAGS_FOLDER/crypto_dag.py', '--cfg-path', '/tmp/tmpdo1txlmn']
[2025-02-13T20:59:45.678+0000] {standard_task_runner.py:105} INFO - Job 14887: Subtask fetch_and_store_crypto_data
[2025-02-13T20:59:45.710+0000] {task_command.py:467} INFO - Running <TaskInstance: crypto_data_collection.fetch_and_store_crypto_data scheduled__2023-11-27T23:17:00+00:00 [running]> on host c6c2d3336250
[2025-02-13T20:59:45.783+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_data_collection' AIRFLOW_CTX_TASK_ID='fetch_and_store_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-27T23:17:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-27T23:17:00+00:00'
[2025-02-13T20:59:45.784+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T20:59:45.833+0000] {logging_mixin.py:190} INFO - Erreur lors de la récupération des données CoinGecko : 429 Client Error: Too Many Requests for url: https://api.coingecko.com/api/v3/simple/price?ids=bitcoin%2Cethereum&vs_currencies=usd
[2025-02-13T20:59:45.834+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-13T20:59:45.842+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T20:59:45.843+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=crypto_data_collection, task_id=fetch_and_store_crypto_data, run_id=scheduled__2023-11-27T23:17:00+00:00, execution_date=20231127T231700, start_date=20250213T205945, end_date=20250213T205945
[2025-02-13T20:59:45.891+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T20:59:45.906+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T20:59:45.910+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
