[2025-02-12T20:46:35.312+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T20:46:35.324+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_flow.fetch_crypto_data scheduled__2024-10-20T00:00:00+00:00 [queued]>
[2025-02-12T20:46:35.330+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_flow.fetch_crypto_data scheduled__2024-10-20T00:00:00+00:00 [queued]>
[2025-02-12T20:46:35.331+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-12T20:46:35.343+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_crypto_data> on 2024-10-20 00:00:00+00:00
[2025-02-12T20:46:35.348+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1556) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-12T20:46:35.348+0000] {standard_task_runner.py:72} INFO - Started process 1563 to run task
[2025-02-12T20:46:35.348+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'crypto_flow', 'fetch_crypto_data', 'scheduled__2024-10-20T00:00:00+00:00', '--job-id', '387', '--raw', '--subdir', 'DAGS_FOLDER/crypto_dag.py', '--cfg-path', '/tmp/tmp4f7b8y1_']
[2025-02-12T20:46:35.349+0000] {standard_task_runner.py:105} INFO - Job 387: Subtask fetch_crypto_data
[2025-02-12T20:46:35.388+0000] {task_command.py:467} INFO - Running <TaskInstance: crypto_flow.fetch_crypto_data scheduled__2024-10-20T00:00:00+00:00 [running]> on host 3c24d57f5cd3
[2025-02-12T20:46:35.511+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_flow' AIRFLOW_CTX_TASK_ID='fetch_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-20T00:00:00+00:00'
[2025-02-12T20:46:35.512+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-12T20:46:35.583+0000] {logging_mixin.py:190} INFO - Données récupérées : {'status': {'error_code': 429, 'error_message': "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2025-02-12T20:46:35.584+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-12T20:46:35.595+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-12T20:46:35.595+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=crypto_flow, task_id=fetch_crypto_data, run_id=scheduled__2024-10-20T00:00:00+00:00, execution_date=20241020T000000, start_date=20250212T204635, end_date=20250212T204635
[2025-02-12T20:46:35.682+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T20:46:35.695+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T20:46:35.698+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
