[2025-02-13T20:56:42.206+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T20:56:42.225+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_collection.fetch_and_store_crypto_data scheduled__2023-11-10T04:17:00+00:00 [queued]>
[2025-02-13T20:56:42.234+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_collection.fetch_and_store_crypto_data scheduled__2023-11-10T04:17:00+00:00 [queued]>
[2025-02-13T20:56:42.234+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-13T20:56:42.253+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_and_store_crypto_data> on 2023-11-10 04:17:00+00:00
[2025-02-13T20:56:42.265+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2863) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-13T20:56:42.266+0000] {standard_task_runner.py:72} INFO - Started process 2870 to run task
[2025-02-13T20:56:42.265+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_collection', 'fetch_and_store_crypto_data', 'scheduled__2023-11-10T04:17:00+00:00', '--job-id', '14460', '--raw', '--subdir', 'DAGS_FOLDER/crypto_dag.py', '--cfg-path', '/tmp/tmpi_tq3np0']
[2025-02-13T20:56:42.267+0000] {standard_task_runner.py:105} INFO - Job 14460: Subtask fetch_and_store_crypto_data
[2025-02-13T20:56:42.304+0000] {task_command.py:467} INFO - Running <TaskInstance: crypto_data_collection.fetch_and_store_crypto_data scheduled__2023-11-10T04:17:00+00:00 [running]> on host c6c2d3336250
[2025-02-13T20:56:42.396+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_data_collection' AIRFLOW_CTX_TASK_ID='fetch_and_store_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T04:17:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-10T04:17:00+00:00'
[2025-02-13T20:56:42.397+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T20:56:42.477+0000] {logging_mixin.py:190} INFO - Erreur lors de la récupération des données CoinGecko : 429 Client Error: Too Many Requests for url: https://api.coingecko.com/api/v3/simple/price?ids=bitcoin%2Cethereum&vs_currencies=usd
[2025-02-13T20:56:42.477+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-13T20:56:42.486+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T20:56:42.487+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=crypto_data_collection, task_id=fetch_and_store_crypto_data, run_id=scheduled__2023-11-10T04:17:00+00:00, execution_date=20231110T041700, start_date=20250213T205642, end_date=20250213T205642
[2025-02-13T20:56:42.520+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T20:56:42.526+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
